# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180408_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='BalanceAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='BranchCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='DeliveryTerms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='EsugamaNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='FrieghtTerms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='GrossWeight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='InvoiceType',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='LRNoAndDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='PaymentTerms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='RepName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='StateCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TaxAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TotalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TransactionDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TransportMode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Transporter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
