# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180408_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='NoOfPacks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
