# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180408_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='RoundOff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
