# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoicedetails_roundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='BalanceAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='RoundOff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TaxAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='TotalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
