# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20180425_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='CashDisc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='CrDrNote',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='InvoiceNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
