# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('BranchID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BranchCode', models.CharField(max_length=10)),
                ('BranchName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('IsMainBranch', models.IntegerField()),
                ('OpenDate', models.DateTimeField(default=None)),
                ('SalesGL', models.CharField(max_length=50)),
                ('PurchaseGL', models.CharField(max_length=50)),
                ('MiscGL', models.CharField(max_length=50)),
            ],
        ),
    ]
