# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_auth', '0002_branchdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdetails',
            name='Email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='GSTNo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
