# Generated by Django 2.0.1 on 2018-01-27 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='ManageOrder',
            fields=[
                ('OrderNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('GeneratedOrderNumber', models.CharField(max_length=100, unique='True')),
                ('OrderRaisedDate', models.DateTimeField()),
                ('OrderFor', models.CharField(max_length=50)),
                ('CustomerNumber', models.CharField(max_length=50)),
                ('OrderStatus', models.CharField(max_length=50)),
                ('Comments', models.CharField(max_length=250)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateField(default=datetime.datetime(2018, 1, 27, 20, 57, 31, 896712))),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderQty', models.BigIntegerField()),
                ('DispatchQty', models.BigIntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=4, max_digits=15)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TaxPerProduct', models.DecimalField(decimal_places=4, max_digits=15)),
                ('TotalAmount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('Comments', models.CharField(max_length=250)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateField(default=datetime.datetime(2018, 1, 27, 20, 57, 31, 912339))),
                ('OrderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.ManageOrder')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('ShippingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=500)),
                ('PinCode', models.IntegerField()),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateField(default=datetime.datetime(2018, 1, 27, 20, 57, 31, 896712))),
            ],
        ),
    ]
