# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageorder',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 10, 41, 46, 416154)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 10, 41, 46, 419109)),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 10, 41, 46, 417637)),
        ),
    ]
