# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_auto_20180131_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageorder',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 2, 4, 4, 59, 43, 439771)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 2, 4, 4, 59, 43, 442258)),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='EnteredDate',
            field=models.DateField(default=datetime.datetime(2018, 2, 4, 4, 59, 43, 441133)),
        ),
    ]
