# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-29 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0004_auto_20180428_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Tax',
        ),
    ]
