# Generated by Django 2.0 on 2018-01-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=1000)),
                ('WebSite', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('CustomerType', models.CharField(max_length=50)),
                ('TinNumber', models.CharField(max_length=100)),
                ('CstNumber', models.CharField(max_length=100)),
                ('GstNumber', models.CharField(max_length=100)),
                ('PanNumber', models.CharField(max_length=50, unique=True)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerDetails'),
        ),
    ]
