# Generated by Django 2.0 on 2018-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Status',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
