# Generated by Django 2.0 on 2018-01-20 06:03

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180103_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='PhoneNumber',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='CustomerNumber',
            field=models.CharField(default="NULL", editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='ReferenceCustomerNumber',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
