# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 18:34
from __future__ import unicode_literals

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180120_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='CustomerNumber',
            field=models.CharField(default=customer.models.increment_customernumber, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='PanNumber',
            field=models.CharField(max_length=50),
        ),
    ]
