# Generated by Django 2.0 on 2018-01-21 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=250, unique=True)),
                ('Description', models.CharField(max_length=500)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=datetime.date(2018, 1, 21))),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=50, unique=True)),
                ('ProductName', models.CharField(max_length=250, unique=True)),
                ('Description', models.CharField(max_length=1000)),
                ('HsnSacCode', models.CharField(max_length=50, unique=True)),
                ('Units', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('MoQ', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=datetime.date(2018, 1, 21))),
                ('CategoryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductCategory')),
            ],
        ),
    ]
