# Generated by Django 2.0 on 2018-01-21 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 12, 39, 34, 867364)),
        ),
        migrations.AlterField(
            model_name='products',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 12, 39, 34, 868677)),
        ),
    ]
