# Generated by Django 2.0 on 2018-01-22 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180121_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 12, 18, 54, 660446)),
        ),
        migrations.AlterField(
            model_name='products',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 12, 18, 54, 661835)),
        ),
    ]
