# Generated by Django 2.0 on 2018-01-22 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180122_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 13, 6, 2, 301583)),
        ),
        migrations.AlterField(
            model_name='products',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 13, 6, 2, 302964)),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.TextField(blank=True),
        ),
    ]
