# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180122_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=50)),
                ('UnitPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('MarginAllowed', models.DecimalField(decimal_places=4, max_digits=10)),
                ('FinalPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('EffectiveDate', models.DateTimeField(default=datetime.datetime(2018, 2, 4, 5, 1, 19, 706403))),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=datetime.datetime(2018, 2, 4, 5, 1, 19, 706492))),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=50)),
                ('AvailableQty', models.BigIntegerField()),
                ('EnteredBy', models.CharField(max_length=100)),
                ('EnteredDate', models.DateTimeField(default=datetime.datetime(2018, 2, 4, 5, 1, 19, 705245))),
            ],
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 5, 1, 19, 702299)),
        ),
        migrations.AlterField(
            model_name='products',
            name='EnteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 5, 1, 19, 703956)),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products'),
        ),
    ]
