# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180204_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='EnteredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='EffectiveDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='EnteredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='EnteredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='EnteredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
